# 예외처리

예외란, 프로그램이 목적 또는 의도한 대로 동작하지 않고, 프로그램이 예정된 동작을 수행할 수 없는 경우가 발생하거나
미리 상정된 오류가 발생하는 것을 통틀어 예외(Exception)라고 일컫음.

프로그램 개발시 목적에 맞는 코드를 작성하는 것만큼, 프로그램이 의도한대로 흘러가지 않을 경우를 대비한 예외처리는 중요.

* 예외처리를 해야 하는 이유.
  
  ```
  >>> def check_even(number):
  ...    
  ...    if number % 2 == 0:
  ...        print(str(number) + "는 짝수입니다.")
  ...    elif number % 2 == 1:
  ...        print(str(number) + "는 홀수입니다.")
  ...    else:
  ...        print("짝수와 홀수의 판별유무는 2로 나누어 떨어지거나 아닌 정수입니다. 이상한 걸 입력하지 마세요.")
  ...
  >>> check_even("메롱")
  야이 ㅅㄲ야
  ```

※ 특히, Python 언어 특성상 변수나 인자에 타입의 제한없이 다양한 자료형이 올 수 있음으로 더욱 중요해 보임.

## 1. try ~ except

Python 에서 기본적인 예외처리 구문은 try 문과 except 문으로 이루어짐.


### 1.1 기본 형태

* try 블록 수행 중 오류가 발생하면 except 블록이 수행.
  하지만 try 블록에서 오류가 발생하지 않는다면 except 블록은 수행되지 않는다.
  
  ```
  try:
      실행할 코드
      ...
  except 발생 예외:
      오류 발생시 실행할 코드
      ...
  ```
  
  ```
  >>> 1 / 0
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ZeroDivisionError: division by zero
  ```
  
  ```
  >>> try:
  ...     1 / 0
  ... except Exception:
  ...     print("예외가 발생했습니다.")
  ...
  예외가 발생했습니다.
  ```


### 1.2 다양한 형태

* 모든 예외는 Exception 의 하위 클래스로 Exception 으로 모든 예외에 대처가능.
* 예외명 생략시 모든 예외 발생에 대비함.
  
  ```
  try:
      실행할 코드
      ...
  except:
      예외 발생시 실행할 코드
      ...
  ```
  
  ```
  >>> try:
  ...     print(x)
  ... except:
  ...     print("예외가 발생했습니다.")
  ...
  예외가 발생했습니다.
  ```

* 다양한 에러 유형에 각각 대처 (except 여러개 활용 가능)
  
  ```
  try:
      실행할 코드
      ...
  except 발생 예외1:
      예외1 발생시 실행할 코드
      ...
  except 발생 예외2:
      예외2 발생시 실행할 코드
      ...
  ```
  
  ```
  >>> try:
  ...     print(1 / 0)
  ... except ZeroDivisionError:
  ...     print("0으로 나눌 수 없습니다.")
  ... except:
  ...     print("예외가 발생했습니다.")
  ...
  0으로 나눌 수 없습니다.
  ```
  
* 튜플로 여러 개의 예외를 묶어서 하나의 except 문으로 작성 가능.

  ```
  >>> try:
  ...     print(x)
  ... except (ZeroDivisionError, NameError, AttributeError):
  ...     print("예외가 발생했습니다.")
  ...
  예외가 발생했습니다.
  ```
  
* as 키워드로 별칭 부여 가능.
  
  ```
  try:
     실행할 코드
     ...
  except 발생 예외 as 별칭:
      예외 발생시 실행할 코드
      ...
  ```
  
  ```
  >>> try:
  ...     print(1 / 0)
  ... except Exception as e:
  ...     print(e.args)
  ...
  ('division by zero',)
  ```


### 1.3 예외의 종류

* 기본적으로 Python 에 자주 발생하는 몇몇 예외들이 이미 정의되어 있음.

  |예외|원인|
  |---|---|
  |SyntaxError|잘못된 문법|
  |NameError|참조변수 없음|
  |ZeroDivisionError|0으로 나눌 수 없음|
  |IndexError|인덱스 범위 벗어남|
  |ValueError|참조 값이 없음|
  |KeyError|키 없음 에러 (주로 딕셔너리 사용시)|
  |AttributeError|모듈, 클래스의 잘못된 속성 사용함|
  |FileNotFoundError|파일을 찾을 수 없음|
  |TypeError|타입이 맞지 않음|


### 1.4 else

* 예외가 **발생하지 않았을 경우** 실행.

  ```
  try:
      실행할 코드
      ...
  except 발생 예외:
      예외 발생시 실행 코드
      ...
  else:
      예외 발생하지 않을 경우 실행 코드
      ...
       
  ```
  
  ```
  >>> name = "홍길동"
  >>> try:
  ...     print(f"내 이름은 {name}입니다.")
  ... except:
  ...     print("예외가 발생했습니다.")
  ... else:
  ...     print("반갑습니다.")
  ...
  내 이름은 홍길동입니다.
  반갑습니다.
  ```
  
* 예외 발생시에는 else 문은 실행되지 않음.

  ```
  >>> del name
  >>> try:
  ...     print(f"내 이름은 {name}입니다.")
  ... except:
  ...     print("예외가 발생했습니다.")
  ... else:
  ...     print("반갑습니다.")
  ...
  예외가 발생했습니다.
  ```
  
  ```
  >>> try:
  ...     
  ```


### 1.5 finally

* 예외 **발생유무와 상관없이 무조건 마지막에 실행**.

  ```
  try:
      실행할 코드
      ...
  except 발생 예외:
      예외 발생시 실행 코드
      ...
  else:
      예외 발생하지 않을 경우 실행 코드
      ...
  finally:
      예외 발생유무와 상관없이 마지막에 실행할 코드
      ...
  
  ```
  
  ```
  >>> a = (1, 2, 3, 4, 5)
  >>> try:
  ...     a[5] = 6
  ... except Exception as e:
  ...     print("예외가 발생했습니다.", str(e))
  ... finally:
  ...     print("try 문의 수행이 종료되었습니다.")
  ...
  예외가 발생했습니다. 'tuple' object does not support item assignment
  try 문의 수행이 종료되었습니다.
  ```

<br />

## 2. 강제 예외 발생

프로그램 상 수행이 불가능한 것은 아니지만, 개발 목적에서 벗어난 상황이 발생한 경우, 강제로 예외를 발생시켜 처리하는 것.


### 2.1 raise

* raise 키워드를 통해 예외를 발생시킬 수 있음.

  ```
  raise 예외명
  ```

  ```
  >>> x = "hello"
  >>> if not type(x) is int:
  ...     raise TypeError("정수형만 입력 가능합니다.")
  ...
  Traceback (most recent call last):
    File "<stdin>", line 2, in <module>
  TypeError: 정수형만 입력 가능합니다.
  ```
  
* 예외처리를 고려한 함수의 일반적인 모습
  
  ```
  >>> def check_even(number):
  ...    try:
  ...        if not number.__class__ is int:
  ...            raise TypeError("정수만 입력해주세요.")
  ...    except Exception as e:
  ...        print(str(e))
  ...    else:
  ...        if number % 2 == 0:
  ...            print("%d는 짝수입니다." % number)
  ...        elif number % 2 == 1:
  ...            print("%d는 홀수입니다." % number)
  ...    finally:
  ...        print("check_even() 함수가 종료되었습니다.")
  ...
  >>> check_even("메롱")
  정수만 입력해주세요.
  check_even() 함수가 종료되었습니다.
  ```


### 2.2 사용자 정의 예외

기본적으로 Python 에 정의된 예외 외에 사용자가 직접 정의하여 생성할 수 있음.

* Exception 클래스를 상속받아서 예외 정의 가능.

  ```
  class 예외명(Exception):
      def __init__(self):
          super().__init__('에러메시지')
  ```
  
  ```
  >>> class MinusNumberError(Exception):
  ...     def __init__(self, msg="0보다 작은 숫자입니다."):
  ...         super().__init__(msg)
  ...
  >>> x = -10
  >>> try:
  ...     if x < 0:
  ...         raise MinusNumberError
  ... except MinusNumberError as e:
  ...     print(str(me))
  ... except:
  ...     print("예외가 발생했습니다.")
  ... else:
  ...     print("x는 0보다 큽니다.")
  ...
  0보다 작은 숫자입니다.
  ```

<br />

## [예제](https://github.com/tnehf18/chatbot/blob/master/ch06_exception/)